service: enemy-losses-slackbot
frameworkVersion: "3"
useDotenv: true

provider:
  name: aws
  runtime: nodejs18.x
  timeout: 30
  memorySize: 512
  environment:
    SLACK_BOT_TOKEN: ${env:SLACK_BOT_TOKEN}
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_CHANNEL_ID: ${env:SLACK_CHANNEL_ID}
custom:
  serverlessPluginTypescript:
    tsConfigFileLocation: "./tsconfig.json"

plugins:
  - serverless-plugin-typescript
  - serverless-offline

functions:
  slack:
    handler: app.handler
    events:
      # - schedule: rate(10 minutes)
      - schedule: cron(10 9 * * ? *)
